services:
  postgres-service:
    container_name: "postgres-service"
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres-service-data:/var/lib/postgresql/data
    networks:
      - effective-mobile-task-network

  service:
    container_name: "service"
    build: .
    restart: always
    depends_on:
      postgres-service:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - .:/app
    networks:
      - effective-mobile-task-network

networks:
  effective-mobile-task-network:
    driver: bridge

volumes:
  postgres-service-data:
